language: node_js
node_js:
  - 18

services:
  - docker

script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed trishubham09/udagram-api-feed:v1
  - docker tag udagram-api-user trishubham09/udagram-api-user:v1
  - docker tag udagram-frontend trishubham09/udagram-frontend:v1
  - docker tag udagram-reverseproxy trishubham09/udagram-reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push trishubham09/udagram-api-feed:v1
  - docker push trishubham09/udagram-api-user:v1
  - docker push trishubham09/udagram-frontend:v1
  - docker push trishubham09/udagram-reverseproxy:v1
  
